apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/network-policies.yaml
  - base/app-secret.yaml
  - base/redis/redis.yaml
  - base/postgres/postgres.yaml
  - base/participate/participate.yaml
  - base/submissions/submissions.yaml
  - base/pick-winner/pick-winner.yaml
  - base/sync-worker/sync-worker.yaml
  - base/ingress/ingress.yaml
