apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr
  namespace: sunnymor
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoia21heWVyMTAiLCJwYXNzd29yZCI6ImdocF8zV3FOM0ozbnJDVUJ5STUwbWxSZzZYekRCSGtlZU0zcU5QZnoiLCJhdXRoIjoiYTIxaGVXVnlNVEE2WjJod1h6TlhjVTR6U2pOdWNrTlZRbmxKTlRCdGJGSm5ObGg2UkVKSWEyVmxUVE54VGxCbWVnPT0ifX19
