name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  # Participate Service
  build-and-push-participate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image for participate service
      env:
        BUILD_ID: ${{ github.run_id }}
        REPO_NAME: ghcr.io/${{ github.repository_owner }}/sunnymor-participate-app
      run: |
        echo "Building participate Docker image with tags: $BUILD_ID and latest"
        docker build -f participate.dockerfile -t $REPO_NAME:$BUILD_ID -t $REPO_NAME:latest .

    - name: Push Docker image for participate service
      env:
        BUILD_ID: ${{ github.run_id }}
        REPO_NAME: ghcr.io/${{ github.repository_owner }}/sunnymor-participate-app
      run: |
        echo "Pushing participate Docker images to GHCR.io"
        docker push $REPO_NAME:$BUILD_ID
        docker push $REPO_NAME:latest

  # Submissions Service
  build-and-push-submissions:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image for submissions service
      env:
        BUILD_ID: ${{ github.run_id }}
        REPO_NAME: ghcr.io/${{ github.repository_owner }}/sunnymor-submissions-app
      run: |
        echo "Building submissions Docker image with tags: $BUILD_ID and latest"
        docker build -f submissions.dockerfile -t $REPO_NAME:$BUILD_ID -t $REPO_NAME:latest .

    - name: Push Docker image for submissions service
      env:
        BUILD_ID: ${{ github.run_id }}
        REPO_NAME: ghcr.io/${{ github.repository_owner }}/sunnymor-submissions-app
      run: |
        echo "Pushing submissions Docker images to GHCR.io"
        docker push $REPO_NAME:$BUILD_ID
        docker push $REPO_NAME:latest

  # Pick Winner Service
  build-and-push-sync-postgres:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image for pick_winner service
      env:
        BUILD_ID: ${{ github.run_id }}
        REPO_NAME: ghcr.io/${{ github.repository_owner }}/sunnymor-sync-worker-app
      run: |
        echo "Building sync-postgres Docker image with tags: $BUILD_ID and latest"
        docker build -f sync_postgres.dockerfile -t $REPO_NAME:$BUILD_ID -t $REPO_NAME:latest .

    - name: Push Docker image for sync-postgres service
      env:
        BUILD_ID: ${{ github.run_id }}
        REPO_NAME: ghcr.io/${{ github.repository_owner }}/sunnymor-sync-worker-app
      run: |
        echo "Pushing sync-postgres Docker images to GHCR.io"
        docker push $REPO_NAME:$BUILD_ID
        docker push $REPO_NAME:latest

        # Pick Winner Service
  build-and-push-pick-winner:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image for pick_winner service
      env:
        BUILD_ID: ${{ github.run_id }}
        REPO_NAME: ghcr.io/${{ github.repository_owner }}/sunnymor-pick-winner-app
      run: |
        echo "Building pick_winner Docker image with tags: $BUILD_ID and latest"
        docker build -f pick_winner.dockerfile -t $REPO_NAME:$BUILD_ID -t $REPO_NAME:latest .

    - name: Push Docker image for pick_winner service
      env:
        BUILD_ID: ${{ github.run_id }}
        REPO_NAME: ghcr.io/${{ github.repository_owner }}/sunnymor-pick-winner-app
      run: |
        echo "Pushing pick_winner Docker images to GHCR.io"
        docker push $REPO_NAME:$BUILD_ID
        docker push $REPO_NAME:latest
